name: Features
on:
  push:
    branches:
      - main

jobs:
  features:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Features
      uses: devcontainers/action@v1
      with:
        publish-features: "true"
        base-path-to-features: "./features"
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
