name: Features
on:
  push:
    branches:
      - main

jobs:
  features:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4

    - name: Features
      uses: devcontainers/action@v1
      with:
        publish-features: "true"
        base-path-to-features: "./features"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
