name: Features
on:
  push:
    branches:
      - main
      
permissions:
  packages: admin
  contents: write
  pull-requests: write

jobs:
  features:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Features
      uses: devcontainers/action@v1
      with:
        publish-features: "true"
        base-path-to-features: "./features"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
